In [5]:
import numpy as np

In [6]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[2]

np.int64(13)

In [8]:
arr[2:6]

array([13, 14, 15, 16])

In [9]:
arr_slice = arr[2::2]
arr_slice

array([13, 15, 17, 19])

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0,4]

np.int64(5)

In [12]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [13]:
slice = arr[3:5,3:5]
slice

array([[19, 20],
       [24, 25]])

In [14]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [16]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])