In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
list[1,2,3,4]

list[1, 2, 3, 4]

In [4]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [13]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
np.random.rand(5)

array([0.63298848, 0.52117672, 0.81275101, 0.0132121 , 0.95802632])

In [19]:
np.random.randn(5)

array([-0.38081937,  0.14592129,  0.89924804, -0.51300394,  0.83761518])

In [20]:
np.random.randint(10,20,10)

array([13, 13, 15, 17, 15, 10, 14, 13, 14, 16], dtype=int32)

In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.shape

(3, 3)

In [32]:
arr.min()

np.int64(1)

In [33]:
arr.max()

np.int64(9)

In [34]:
arr.sum()

np.int64(45)

In [35]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [36]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [38]:
arr.mean()

np.float64(5.0)

In [39]:
arr.std()

np.float64(2.581988897471611)

In [41]:
arr.argmax()

np.int64(8)

In [42]:
arr.argmin()

np.int64(0)

In [43]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])